language: haxe

sudo: true

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development

branches:
  only:
    - develop

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install hxlog
  - haxelib path hxlog
  - haxelib dev hxmake .
  - haxelib path hxmake

script:
  - haxelib run hxmake _
  - hxmake _
  - hxmake haxe
