version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  - cinst haxe -y
  - RefreshEnv
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"

build: off

branches:
  only:
    - develop

test_script:
  - haxelib dev hxmake .
  - haxelib run hxmake _
  - hxmake _
  - hxmake haxe